# Generated by Django 4.2.7 on 2024-01-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'Product Gallery', 'verbose_name_plural': 'Product Gallery'},
        ),
    ]
